name: project-env
channels:
  - conda-forge
dependencies:
  - python=3.12
  - pip
  - pip:
    - ipykernel # Must be specified for .devcontainers to work correctly
    - notebook # Must be specified for .devcontainers to work correctly
    - ipywidgets
    - pre-commit
    - tqdm
    - watermark
